services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: docchat-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dasturchi_05
      POSTGRES_PASSWORD: 571632
      POSTGRES_DB: docchat
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dasturchi_05 -d docchat"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: docchat-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
